### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by fvdsn** [danielbruce/entypo#8] opened 2012-10-30 14:14 UTC
Hi, the font is very beautiful but difficult to work with because of the size of the boxes/padding around the icon.  When integrated with regular text, the icon is too small. And if you make it bigger, the tall box will move the entire line down. And with a variable width, making a simple square button with a centered icon involves a lot of css trickery. 

It would be perfect if there was a 'allcaps monotype' version of the font where all the font boxes are square with the icon centered.

**Comment by puzrin** [comment] 2012-10-30 14:37
Why don't you set fixed width with CSS ? See `preview` tab in firebug. Something like this:

``` css
display: inline-block;
text-align: center;
width: 1.1em;
```

Also, don't forget about line-height for proper vertical alignment. Does it solves your problem or i missed something?

**Comment by 9mm** [comment] 2012-11-02 01:54
I agree with fvdsn, the spacing is such that it makes the font unusable. There are massive differences between PC and Mac. I have tried every conceivable combination of line-height, height, vertical-align, padding, etc. 

PC:
![pic](http://i.stack.imgur.com/cv543.png)

Mac:
http://i.stack.imgur.com/ecieM.png

I believe this is because there is way too much space, so the font-size much be much bigger than normal (40px or more for a line of text which should be 14px high). Thus, I guess different browsers render this 'leftover' space differently, I have no idea.

**Comment by puzrin** [comment] 2012-11-02 06:31
Do you have such bug on fontello site itself? Look at download & dropdown buttons.

I can't say anything about your examples. Need to see sources of CSS/HTML.

**Comment by 9mm** [comment] 2012-11-02 06:39
To be honest I have no idea why it works on fontello, it seems to be working there...

I spent the last 2 hours already converting them to sprites so it's not really relevant anymore :(

But where I saw it was here: http://entypo.com/

See how large the font must be (40px or 4em) to show something which is about 14px high. You can see just using inspector how much space it takes up. if you set identical settings in pc vs mac, you will see how they vary greatly because of that.

However, on fontello it seems the font corresponds properly. I have no idea why or if they're related or what, but I wish I would have found fontello hours ago :/

**Comment by puzrin** [comment] 2012-11-02 07:29
If your issue it not fontello-related - it would be better to discuss in fontello google group. Post there links to your example (html + css), and i'll wry to find, where is your problem in.

**Comment by joshnh** [comment] 2012-11-04 22:44
I am experiencing the same problem; huge discrepancies between Windows and OS X with line-height rendering. This is Entypo specific, and I'm not using any weird CSS; just basic line-height/font-size stuff.

**Comment by 9mm** [comment] 2012-11-04 22:48
i had to ditch entypo altogether it was so bad. shame, cause its a really awesome icon set

**Comment by puzrin** [comment] 2012-11-05 01:03
Once again. I need HTML/CSS examples to reproduce problem and to be sure that it's not mistake in CSS. Please, be more constructive.

**Comment by 9mm** [comment] 2012-11-05 01:10
I dont really have any css or html examples, it just is. Here's a little test though that you can do:
1. Go to http://entypo.com/
2. On the Entypo website they use `<li>` elements, so use chrome inspector set the background color of each li to red. You probably want to delete float while youre at it, maybe set only 10px margin, and set them to block or inline-block, just to make it easier to do this experiment.
3. Open up both a Windows and OSX instance via VM or whatever
4. set the width and height the icons the same (just big enough so it contains the borders of the icons), for me this was: `width: 20px; height: 20px; background: red;` try to make it look like the screenshots I posted above
5. Now do the identical thing in the other browser, and you will see even though it is identical css, the icons will be wildly different.
6. From my experimenting, any combination of height, line-height, display, etc that I tried didn't alleviate the issue, it would either make it too far up on one OS and right on the other, or too low on one and right on the other.

**Comment by joshnh** [comment] 2012-11-05 01:17
@puzrin The bug is clearly visible when viewing the Enypo homepage on Windows. Check out the CTA buttons: http://www.entypo.com/

On a Mac, they are centered vertically. On Windows machines, they are not (instead, sitting at the bottom of the buttons).

As far as I can tell, it is a rendering issue not easily solvable using CSS.

**Comment by puzrin** [comment] 2012-11-05 01:26
Guys, i'm serious. I need your HTML/CSS samples, to make sure, that it's not your mistake. Because there are no problems with fontello site itself (it uses entypo). My time is a bit limited, and providing minimalistic sample is the best way to help solving problem, if it exists.

**Comment by joshnh** [comment] 2012-11-05 01:31
@puzrin Firstly, I have given you a direct link to the issue. I'm not sure what further instructions you require?

Secondly, if the issue is present on the homepage of the icon font (Entypo, not Fontello), I'd be willing to bet that it isn't a simple HTML/CSS issue on my end.

**Comment by puzrin** [comment] 2012-11-05 01:56
@joshnh Font from that link is not generated by fontello. It can not be valid sample. If you think, that fontello generate buggy font, please, provide this things:
1. HTML/CSS example with fontello-generated font, hosted somewhere. That demonstrates your problem.
2. List of OS/Browsers, that reproduces your bug.

**Comment by joshnh** [comment] 2012-11-05 02:22
@puzrin I'm not using Fontello, I'm using what I downloaded directly from Entypo. Nothing I have mentioned has anything to do with Fontello. This is the Entypo repository is it not?

**Comment by puzrin** [comment] 2012-11-05 05:42
OMG... my apologises... I've mixed up repos...

Entypo has 2 sources:
1. Official, http://www.entypo.com/ , all done by Daniel Bruce . Has version 2.0 now.
2. "Almost official". Maintained by me https://github.com/danielbruce/entypo & https://github.com/fontello/entypo. I've asked Daniel to send me separate images, to build font for fontello. Here are still someting intermediate between 1.0 and 2.0 . Only those parts, needed for fontello (no EPS, OTF and so on)

If you have questions about font from entypo.com, you'd better write to Daniel directly.

As alternative, you can try to build font with fontello, use provided CSS, and if the same bug exists, report it here https://github.com/fontello/fontello/issues?sort=updated&state=open , with your examples. Then i'll try to help.

Sorry again for confusion.

**Comment by joshnh** [comment] 2012-11-05 08:57
I was under time restraint and had to use another typeface. Thanks anyway.

**Comment by fvdsn** [comment] 2012-11-06 16:30
Hi, the issue is really simple, it's that the "bounding box"  of the font has a height that is approximately two times as high as the icon itself. And that the icon itself are much too small compared to other fonts at the same point size. Since I cannot attach images to this post i'll attempt some schematics :)

```
 OTHER ICON FONTS          ENTYPO
 +------------+            +----+ 
 |   ######   |            |    |
 |  ########  |            |    |
 |  ########  |            | ## |
 |   ######   |            | ## |
 +------------+            +----+

 AN ENTYPO ICON MIXED WITH TEXT :

          +-+  <- higher box for entypo glyphs
 +--------| |----+
 |abcdefgh|#|ijkl|
 +--------+-+----+    
```

The higher bounding box will push down the line and the only way to fix that is to put the entypo icon absolutely positionned inside another correctly sized inline block element. (and that's not really pretty...) Yes those issue can be fixed with css, but it's not easy to do and I don't really get what is supposed to be the advantage of the current entypo bounding boxes size. 

And those "bounding boxes" looks like they are are generated by your scripts (the svg icons made by daniel are 1000x1000 units squares) . Well the issue exists with the official font as well, but I guess it could easily be fixed by changing the transform settings of your font generating scripts (which I tried but failed to install)

**Comment by 9mm** [comment] 2012-11-06 16:32
Just fyi you can use markdown for images:

`![alt text](image source)`

fvdsn: did you say you had the same problem with fontello? It seemed to work for me with fontello (only the official entypo website had the busted font for osx vs windows). I have already converted everything to sprites, or I would use it again. I will switch it all back though as soon as version 2.0 comes out for entypo. 

Puzrin: Not sure if that's in the works? But that would be awesome

**Comment by fvdsn** [comment] 2012-11-06 17:02
Maybe we are having separate issues... My issue with entypo is that the bounding boxes are too tall compared to their real size.

I've looked at fontello and all the icons on the website suffer from the same issue, so I guess it comes from the fontello script. Just disable width/height on the .glyph css on fontello and look at the dimensions of the red boxes, they all look very thin and tall, and I really don't get what's the advantage of those dimensions.

**Comment by puzrin** [comment] 2012-11-10 00:29
I've updated fontello with "rescaled" Entypo 2.0 icons (rolled back accent/descend, and shifted baseline to 15%).

Let me know if any troubles about scale still exists.

**Comment by jhilden** [comment] 2012-11-11 16:33
I also had scaling problems with the vesion of the font directly taken from http://entypo.com (documented in issue #9), but with using Fontello those issues are gone :)

Thank you so much @puzrin for updating Fontello so quickly and providing this awesome service.

**Comment by alesas** [comment] 2012-11-12 14:44
@puzrin I'll try later in the day. I'll let you know. But thank you already ;)

**Comment by fvdsn** [comment] 2012-11-12 15:09
This looks perfect, thanks a lot :)

**Comment by alesas** [comment] 2012-11-12 21:17
Very cool :) Works like a charm. Thanks!

**Comment by puzrin** [comment] 2012-11-14 17:13
Ok, since all are satisfied, i close this ticket as solved.

**Closed as completed by puzrin** 2012-11-14 17:13 UTC

**Comment by psaikali** [comment] 2012-12-19 03:14
Hi there,
Sorry to "reopen" this conversation, but I'm having the same problem (huge difference between PC / Mac) in my theme (http://murphy-schamberger2692.myshopify.com/).
I downloaded the font via entypo.com, not the "fontello" site that you're speaking about (as I'm using the full character set). Where can I find the updated entire font set? Is the new updated font the one in this repo?
Thanks for your help.

**Comment by 9mm** [comment] 2012-12-19 03:24
dont use entypo, use fontello.com and it will work. fontello apparently isnt really related to entypo.. its just an 'icon builder' where you pick icons from many different sets. he has normalized all the heights, so even though the original entypo is buggered, the fontello version of entypo works great

**Comment by psaikali** [comment] 2012-12-19 03:34
Awesome, I'll use fontello then. Thanks a lot!

**Comment by jmarus** [comment] 2013-01-13 05:11
This might be the wrong place, but it's related. I'm having the same problem with Entypo, where the line-height differs on Windows compared to Mac. I want to download the font using Fontello, but it doesn't let me select all the fonts at once. I have to manually select them all?

**Comment by puzrin** [comment] 2013-01-13 05:13
Click + Move mouse

**Comment by jmarus** [comment] 2013-01-13 05:14
I'm an idiot. Thank you. Great product!

**Comment by hon-chau-ysi** [comment] 2013-01-16 22:24
Thanks for fixing the issue in your product!

**Comment by marcvangend** [comment] 2013-01-18 16:31
@puzrin, @jmarus LOL, I clicked every single entypo icon the other day because I needed the whole set... Thanks for Fontello and thanks for the drag-and-select!

**Comment by klick** [comment] 2013-02-11 16:32
Thank you!
The HTML-entities differ though, i.e. the “x” on the entypo (original) download is `&#10060;` whereas the fontello-version uses `&#10005;`.

**Comment by apappascs** [comment] 2013-11-27 19:00
hello! bug is fixed with jquery ;)

just add this on page:

$(document).ready(function(){
var isMacLike = navigator.platform.match(/(Mac|iPhone|iPod|iPad)/i)?true:false;
var isIOS = navigator.platform.match(/(iPhone|iPod|iPad)/i)?true:false;

if(isMacLike || isIOS)
    {  
        //alert("mac!!!");
        $(".entypoclass").css("margin-top","11px");
    }
    else
        {
           // alert("pc!");
        }
});

**Comment by zenx** [comment] 2014-11-13 12:23
I fixed the font vertical space and made it available here https://github.com/zenx/entypo

**Comment by GabrielToriz** [comment] 2015-05-29 19:12
Excellent zenx!!!

You made my day! The files you made available in which you fixed the problem work completely fine. That was an awesome work! :)
